// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/microhq/auth-srv/proto/oauth2/oauth2.proto

/*
Package go_micro_srv_auth_oauth2 is a generated protocol buffer package.

It is generated from these files:
	github.com/microhq/auth-srv/proto/oauth2/oauth2.proto

It has these top-level messages:
	Token
	AuthorizeRequest
	AuthorizeResponse
	TokenRequest
	TokenResponse
	RevokeRequest
	RevokeResponse
	IntrospectRequest
	IntrospectResponse
*/
package go_micro_srv_auth_oauth2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Token struct {
	AccessToken  string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	TokenType    string   `protobuf:"bytes,2,opt,name=token_type,json=tokenType" json:"token_type,omitempty"`
	RefreshToken string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	ExpiresAt    int64    `protobuf:"varint,4,opt,name=expires_at,json=expiresAt" json:"expires_at,omitempty"`
	Scopes       []string `protobuf:"bytes,5,rep,name=scopes" json:"scopes,omitempty"`
	// metadata associated with the token
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *Token) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *Token) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *Token) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *Token) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type AuthorizeRequest struct {
	// code, token (not supported)
	ResponseType string   `protobuf:"bytes,1,opt,name=response_type,json=responseType" json:"response_type,omitempty"`
	ClientId     string   `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Scopes       []string `protobuf:"bytes,3,rep,name=scopes" json:"scopes,omitempty"`
	State        string   `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
	RedirectUri  string   `protobuf:"bytes,5,opt,name=redirect_uri,json=redirectUri" json:"redirect_uri,omitempty"`
}

func (m *AuthorizeRequest) Reset()                    { *m = AuthorizeRequest{} }
func (m *AuthorizeRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeRequest) ProtoMessage()               {}
func (*AuthorizeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthorizeRequest) GetResponseType() string {
	if m != nil {
		return m.ResponseType
	}
	return ""
}

func (m *AuthorizeRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *AuthorizeRequest) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *AuthorizeRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AuthorizeRequest) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

type AuthorizeResponse struct {
	Code  string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	State string `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	// implicit response
	Token *Token `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *AuthorizeResponse) Reset()                    { *m = AuthorizeResponse{} }
func (m *AuthorizeResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeResponse) ProtoMessage()               {}
func (*AuthorizeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthorizeResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AuthorizeResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AuthorizeResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type TokenRequest struct {
	ClientId     string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	Code         string `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	// password (not supported), client_credentials, authorization_code, refresh_token
	GrantType    string `protobuf:"bytes,4,opt,name=grant_type,json=grantType" json:"grant_type,omitempty"`
	RedirectUri  string `protobuf:"bytes,5,opt,name=redirect_uri,json=redirectUri" json:"redirect_uri,omitempty"`
	RefreshToken string `protobuf:"bytes,6,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	// scopes can be added for client_credentials request
	Scopes []string `protobuf:"bytes,7,rep,name=scopes" json:"scopes,omitempty"`
	// metadata to be stored with a token that's generated
	Metadata map[string]string `protobuf:"bytes,8,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TokenRequest) Reset()                    { *m = TokenRequest{} }
func (m *TokenRequest) String() string            { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()               {}
func (*TokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TokenRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *TokenRequest) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *TokenRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TokenRequest) GetGrantType() string {
	if m != nil {
		return m.GrantType
	}
	return ""
}

func (m *TokenRequest) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

func (m *TokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *TokenRequest) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *TokenRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type TokenResponse struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *TokenResponse) Reset()                    { *m = TokenResponse{} }
func (m *TokenResponse) String() string            { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()               {}
func (*TokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TokenResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type RevokeRequest struct {
	// revoke access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	// revoke via refresh token
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
}

func (m *RevokeRequest) Reset()                    { *m = RevokeRequest{} }
func (m *RevokeRequest) String() string            { return proto.CompactTextString(m) }
func (*RevokeRequest) ProtoMessage()               {}
func (*RevokeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RevokeRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RevokeRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RevokeResponse struct {
}

func (m *RevokeResponse) Reset()                    { *m = RevokeResponse{} }
func (m *RevokeResponse) String() string            { return proto.CompactTextString(m) }
func (*RevokeResponse) ProtoMessage()               {}
func (*RevokeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type IntrospectRequest struct {
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
}

func (m *IntrospectRequest) Reset()                    { *m = IntrospectRequest{} }
func (m *IntrospectRequest) String() string            { return proto.CompactTextString(m) }
func (*IntrospectRequest) ProtoMessage()               {}
func (*IntrospectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IntrospectRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type IntrospectResponse struct {
	Token  *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Active bool   `protobuf:"varint,2,opt,name=active" json:"active,omitempty"`
}

func (m *IntrospectResponse) Reset()                    { *m = IntrospectResponse{} }
func (m *IntrospectResponse) String() string            { return proto.CompactTextString(m) }
func (*IntrospectResponse) ProtoMessage()               {}
func (*IntrospectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *IntrospectResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *IntrospectResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func init() {
	proto.RegisterType((*Token)(nil), "go.micro.srv.auth.oauth2.Token")
	proto.RegisterType((*AuthorizeRequest)(nil), "go.micro.srv.auth.oauth2.AuthorizeRequest")
	proto.RegisterType((*AuthorizeResponse)(nil), "go.micro.srv.auth.oauth2.AuthorizeResponse")
	proto.RegisterType((*TokenRequest)(nil), "go.micro.srv.auth.oauth2.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "go.micro.srv.auth.oauth2.TokenResponse")
	proto.RegisterType((*RevokeRequest)(nil), "go.micro.srv.auth.oauth2.RevokeRequest")
	proto.RegisterType((*RevokeResponse)(nil), "go.micro.srv.auth.oauth2.RevokeResponse")
	proto.RegisterType((*IntrospectRequest)(nil), "go.micro.srv.auth.oauth2.IntrospectRequest")
	proto.RegisterType((*IntrospectResponse)(nil), "go.micro.srv.auth.oauth2.IntrospectResponse")
}

func init() {
	proto.RegisterFile("github.com/microhq/auth-srv/proto/oauth2/oauth2.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 620 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x25, 0xc9, 0x12, 0x9a, 0xdb, 0x16, 0x75, 0xd6, 0x84, 0xa2, 0xa2, 0x89, 0x92, 0x49, 0x50,
	0x01, 0x4b, 0xa5, 0xc2, 0x10, 0x82, 0xa7, 0x3d, 0x80, 0xd4, 0x07, 0x04, 0x0a, 0x43, 0x48, 0x48,
	0xa8, 0xca, 0x5c, 0xaf, 0x8d, 0xba, 0xc6, 0x99, 0xed, 0x54, 0x94, 0x0f, 0xe1, 0x0f, 0x78, 0xe4,
	0xe7, 0xf8, 0x02, 0x14, 0xdb, 0x49, 0xd3, 0x95, 0xad, 0x45, 0x68, 0x4f, 0xcb, 0x3d, 0xbe, 0xbe,
	0xf7, 0x9e, 0x73, 0xee, 0x5c, 0x38, 0x1a, 0xc7, 0x62, 0x92, 0x9d, 0x06, 0x98, 0xce, 0x7a, 0xb3,
	0x18, 0x33, 0x3a, 0xb9, 0xe8, 0x45, 0x99, 0x98, 0x1c, 0x72, 0x36, 0xef, 0xa5, 0x8c, 0x0a, 0xda,
	0xa3, 0x79, 0xdc, 0xd7, 0x7f, 0x02, 0x89, 0x21, 0x6f, 0x4c, 0x03, 0x99, 0x1e, 0x70, 0x36, 0x0f,
	0xf2, 0x93, 0x40, 0x9d, 0xfb, 0xbf, 0x4c, 0xb0, 0x4f, 0xe8, 0x94, 0x24, 0xe8, 0x01, 0x34, 0x22,
	0x8c, 0x09, 0xe7, 0x43, 0x91, 0xc7, 0x9e, 0xd1, 0x31, 0xba, 0x6e, 0x58, 0x57, 0x98, 0x4a, 0xd9,
	0x07, 0x90, 0x67, 0x43, 0xb1, 0x48, 0x89, 0x67, 0xca, 0x04, 0x57, 0x22, 0x27, 0x8b, 0x94, 0xa0,
	0x03, 0x68, 0x32, 0x72, 0xc6, 0x08, 0x9f, 0xe8, 0x12, 0x96, 0xcc, 0x68, 0x68, 0xb0, 0xac, 0x41,
	0xbe, 0xa5, 0x31, 0x23, 0x7c, 0x18, 0x09, 0x6f, 0xa7, 0x63, 0x74, 0xad, 0xd0, 0xd5, 0xc8, 0xb1,
	0x40, 0x77, 0xc1, 0xe1, 0x98, 0xa6, 0x84, 0x7b, 0x76, 0xc7, 0xea, 0xba, 0xa1, 0x8e, 0xd0, 0x00,
	0x6a, 0x33, 0x22, 0xa2, 0x51, 0x24, 0x22, 0xcf, 0xe9, 0x58, 0xdd, 0x7a, 0xff, 0x30, 0xb8, 0x8a,
	0x54, 0x20, 0x3b, 0x05, 0xef, 0x74, 0xfe, 0x9b, 0x44, 0xb0, 0x45, 0x58, 0x5e, 0x6f, 0xbf, 0x86,
	0xe6, 0xca, 0x11, 0x6a, 0x81, 0x35, 0x25, 0x0b, 0x4d, 0x38, 0xff, 0x44, 0x7b, 0x60, 0xcf, 0xa3,
	0xf3, 0xac, 0xe0, 0xa8, 0x82, 0x57, 0xe6, 0x4b, 0xc3, 0xff, 0x69, 0x40, 0xeb, 0x38, 0x13, 0x13,
	0xca, 0xe2, 0xef, 0x24, 0x24, 0x17, 0x19, 0xe1, 0x42, 0x11, 0xe7, 0x29, 0x4d, 0x38, 0x51, 0xd2,
	0x18, 0x05, 0x71, 0x05, 0x4a, 0x75, 0xee, 0x81, 0x8b, 0xcf, 0x63, 0x92, 0x88, 0x61, 0x3c, 0xd2,
	0x75, 0x6b, 0x0a, 0x18, 0x8c, 0x2a, 0xb4, 0xad, 0x15, 0xda, 0x7b, 0x60, 0x73, 0x11, 0x09, 0x22,
	0x85, 0x72, 0x43, 0x15, 0xe4, 0x56, 0x31, 0x32, 0x8a, 0x19, 0xc1, 0x62, 0x98, 0xb1, 0xd8, 0xb3,
	0x95, 0x55, 0x05, 0xf6, 0x89, 0xc5, 0xbe, 0x80, 0xdd, 0xca, 0x98, 0x6a, 0x0c, 0x84, 0x60, 0x07,
	0xd3, 0x51, 0x31, 0x9e, 0xfc, 0x5e, 0x76, 0x30, 0xab, 0x1d, 0x8e, 0xc0, 0x5e, 0x5a, 0x58, 0xef,
	0xdf, 0xdf, 0xa0, 0x75, 0xa8, 0xb2, 0xfd, 0xdf, 0x26, 0x34, 0x14, 0xa0, 0x95, 0x59, 0x21, 0x6d,
	0x5c, 0x22, 0x7d, 0x00, 0x4d, 0x7d, 0xc8, 0x09, 0x66, 0x44, 0xe8, 0x11, 0x1a, 0x0a, 0xfc, 0x28,
	0xb1, 0x72, 0x66, 0xab, 0x32, 0xf3, 0x3e, 0xc0, 0x98, 0x45, 0x89, 0x50, 0x62, 0x2b, 0x69, 0x5c,
	0x89, 0x48, 0xa5, 0x37, 0xcb, 0xb3, 0xbe, 0xaa, 0xce, 0x5f, 0x56, 0x75, 0x69, 0xca, 0xed, 0x15,
	0x53, 0x3e, 0x54, 0x76, 0xb1, 0x26, 0x77, 0xf1, 0xf9, 0x26, 0x7d, 0x94, 0x1c, 0x37, 0xb3, 0x92,
	0x6f, 0xa1, 0xa9, 0x9b, 0x68, 0x9b, 0x4b, 0xf3, 0x8c, 0x7f, 0x32, 0xef, 0x33, 0x34, 0x43, 0x32,
	0xa7, 0xd3, 0x72, 0xad, 0xb7, 0x78, 0x11, 0xd6, 0x74, 0x34, 0xd7, 0x75, 0xf4, 0x5b, 0x70, 0xa7,
	0x28, 0xac, 0x26, 0xf4, 0x5f, 0xc0, 0xee, 0x20, 0x11, 0x8c, 0xf2, 0x94, 0x60, 0xb1, 0x7d, 0x3b,
	0x1f, 0x03, 0xaa, 0xde, 0xfb, 0x2f, 0xbe, 0xb9, 0xbd, 0x11, 0x16, 0xf1, 0x5c, 0x49, 0x5a, 0x0b,
	0x75, 0xd4, 0xff, 0x61, 0x81, 0xf3, 0x5e, 0xe6, 0xa3, 0x33, 0x70, 0xcb, 0xff, 0x22, 0xf4, 0xf8,
	0xea, 0xba, 0x97, 0x5f, 0x84, 0xf6, 0x93, 0xad, 0x72, 0xb5, 0x1a, 0xb7, 0xd0, 0x97, 0xe2, 0x11,
	0x7e, 0xb8, 0xdd, 0x22, 0xb5, 0x1f, 0x6d, 0xcc, 0x2b, 0x6b, 0x7f, 0x05, 0x47, 0xa9, 0x8f, 0xae,
	0xb9, 0xb4, 0x62, 0x7c, 0xbb, 0xbb, 0x39, 0xb1, 0x2c, 0x1f, 0x03, 0x2c, 0x2d, 0x41, 0xd7, 0xf0,
	0x5e, 0x33, 0xbc, 0xfd, 0x74, 0xbb, 0xe4, 0xa2, 0xd5, 0xa9, 0x23, 0x7f, 0xcc, 0x9e, 0xfd, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xa4, 0xdb, 0x28, 0x75, 0x05, 0x07, 0x00, 0x00,
}
