// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/auth-srv/proto/account/account.proto

/*
Package go_micro_srv_auth_account is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/auth-srv/proto/account/account.proto

It has these top-level messages:
	Record
	ReadRequest
	ReadResponse
	CreateRequest
	CreateResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
*/
package go_micro_srv_auth_account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Record struct {
	// uuid
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// service or user
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// service name, username, etc
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	// we leave this blank in responses
	// used for update and create
	ClientSecret string            `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	Metadata     map[string]string `protobuf:"bytes,5,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// unix timestamp
	Created int64 `protobuf:"varint,6,opt,name=created" json:"created,omitempty"`
	// unix timestamp
	Updated int64 `protobuf:"varint,7,opt,name=updated" json:"updated,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Record) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Record) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Record) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Record) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *Record) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Record) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Record) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Account *Record `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadResponse) GetAccount() *Record {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateRequest struct {
	// If id is blank, one will be generated
	Account *Record `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateRequest) GetAccount() *Record {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type UpdateRequest struct {
	// Id and client_id cannot be changed
	Account *Record `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateRequest) GetAccount() *Record {
	if m != nil {
		return m.Account
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type SearchRequest struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Limit    int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset   int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SearchRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *SearchRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchResponse struct {
	Accounts []*Record `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchResponse) GetAccounts() []*Record {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "go.micro.srv.auth.account.Record")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.srv.auth.account.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.srv.auth.account.ReadResponse")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.auth.account.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.auth.account.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.micro.srv.auth.account.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "go.micro.srv.auth.account.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.srv.auth.account.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.srv.auth.account.DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.srv.auth.account.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.srv.auth.account.SearchResponse")
}

func init() {
	proto.RegisterFile("github.com/micro/auth-srv/proto/account/account.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0xdd, 0x24, 0x6d, 0xda, 0xbd, 0xdd, 0x94, 0x32, 0x2c, 0x12, 0x2b, 0x62, 0x8d, 0xa0, 0xf5,
	0xc1, 0x04, 0x2a, 0x82, 0xb8, 0xf8, 0x20, 0xea, 0x83, 0xac, 0x22, 0xcc, 0xe2, 0x83, 0x4f, 0xcb,
	0xec, 0xcc, 0xec, 0x36, 0xd8, 0x66, 0xea, 0x64, 0x52, 0xe8, 0x7f, 0xf2, 0x87, 0xf9, 0x33, 0x24,
	0xf3, 0x51, 0x4d, 0xd0, 0xec, 0x82, 0xfb, 0xd4, 0xdc, 0x8f, 0x73, 0xce, 0xdc, 0x7b, 0x0f, 0x85,
	0x17, 0x57, 0xb9, 0x5a, 0x56, 0x17, 0x29, 0x15, 0xeb, 0x6c, 0x9d, 0x53, 0x29, 0x32, 0x52, 0xa9,
	0xe5, 0xb3, 0x52, 0x6e, 0xb3, 0x8d, 0x14, 0x4a, 0x64, 0x84, 0x52, 0x51, 0x15, 0xca, 0xfd, 0xa6,
	0x3a, 0x8b, 0xee, 0x5e, 0x89, 0x54, 0xb7, 0xa7, 0xa5, 0xdc, 0xa6, 0x35, 0x24, 0xb5, 0x0d, 0xc9,
	0x0f, 0x1f, 0x42, 0xcc, 0xa9, 0x90, 0x0c, 0x8d, 0xc1, 0xcf, 0x59, 0xec, 0xcd, 0xbc, 0xf9, 0x21,
	0xf6, 0x73, 0x86, 0x10, 0xf4, 0xd4, 0x6e, 0xc3, 0x63, 0x5f, 0x67, 0xf4, 0x37, 0xba, 0x07, 0x87,
	0x74, 0x95, 0xf3, 0x42, 0x9d, 0xe7, 0x2c, 0x0e, 0x74, 0x61, 0x68, 0x12, 0x1f, 0x18, 0x7a, 0x04,
	0x91, 0x2d, 0x96, 0x9c, 0x4a, 0xae, 0xe2, 0x9e, 0x6e, 0x38, 0x32, 0xc9, 0x33, 0x9d, 0x43, 0xa7,
	0x30, 0x5c, 0x73, 0x45, 0x18, 0x51, 0x24, 0xee, 0xcf, 0x82, 0xf9, 0x68, 0x91, 0xa5, 0xff, 0x7c,
	0x5e, 0x6a, 0x9e, 0x96, 0x7e, 0xb2, 0x88, 0xf7, 0x85, 0x92, 0x3b, 0xbc, 0x27, 0x40, 0x31, 0x0c,
	0xa8, 0xe4, 0x44, 0x71, 0x16, 0x87, 0x33, 0x6f, 0x1e, 0x60, 0x17, 0xd6, 0x95, 0x6a, 0xc3, 0x74,
	0x65, 0x60, 0x2a, 0x36, 0x9c, 0x9e, 0x40, 0xd4, 0xa0, 0x43, 0x13, 0x08, 0xbe, 0xf1, 0x9d, 0x1d,
	0xbc, 0xfe, 0x44, 0xc7, 0xd0, 0xdf, 0x92, 0x55, 0xe5, 0x46, 0x37, 0xc1, 0x2b, 0xff, 0xa5, 0x97,
	0xdc, 0x87, 0x11, 0xe6, 0x84, 0x61, 0xfe, 0xbd, 0xe2, 0xa5, 0x6a, 0xaf, 0x2c, 0x39, 0x85, 0x23,
	0x53, 0x2e, 0x37, 0xa2, 0x28, 0x39, 0x3a, 0x81, 0x81, 0x9d, 0x44, 0x37, 0x8d, 0x16, 0x0f, 0xaf,
	0x9d, 0x15, 0x3b, 0x44, 0xf2, 0x11, 0xa2, 0xb7, 0x7a, 0x1a, 0xa7, 0xf6, 0x5f, 0x6c, 0x13, 0x18,
	0x3b, 0x36, 0xf3, 0xb8, 0x9a, 0xff, 0x8b, 0xde, 0xc9, 0x6d, 0xf1, 0x3b, 0x36, 0xcb, 0xff, 0x00,
	0xa2, 0x77, 0x7c, 0xc5, 0x7f, 0xf3, 0xb7, 0xb7, 0x35, 0x81, 0xb1, 0x6b, 0xb0, 0x90, 0x02, 0xa2,
	0x33, 0x4e, 0x24, 0x5d, 0x3a, 0x48, 0xc3, 0x6f, 0x5e, 0xcb, 0x6f, 0x7f, 0x33, 0xe8, 0x31, 0xf4,
	0x57, 0xf9, 0x3a, 0x57, 0xda, 0x9c, 0x01, 0x36, 0x01, 0xba, 0x03, 0xa1, 0xb8, 0xbc, 0x2c, 0xad,
	0x25, 0x03, 0x6c, 0xa3, 0xe4, 0x33, 0x8c, 0x9d, 0x9e, 0xbd, 0xd8, 0x6b, 0x18, 0xda, 0x89, 0xca,
	0xd8, 0xd3, 0xf6, 0xbc, 0xc1, 0x12, 0xf6, 0x90, 0xc5, 0xcf, 0x00, 0x06, 0x6f, 0x4c, 0x80, 0xbe,
	0x42, 0xaf, 0x36, 0x03, 0x7a, 0xdc, 0x49, 0xb0, 0x37, 0xd3, 0xf4, 0xc9, 0xb5, 0x7d, 0x76, 0x4b,
	0x07, 0xe8, 0x1c, 0x42, 0x73, 0x4c, 0x34, 0xef, 0x00, 0x35, 0xdc, 0x33, 0x7d, 0x7a, 0x83, 0xce,
	0x3f, 0x05, 0xcc, 0x35, 0x3b, 0x05, 0x1a, 0xf6, 0xe9, 0x14, 0x68, 0x59, 0x43, 0x0b, 0x98, 0xdb,
	0x77, 0x0a, 0x34, 0xfc, 0xd3, 0x29, 0xd0, 0x32, 0x92, 0x16, 0x30, 0xa7, 0xed, 0x14, 0x68, 0xb8,
	0xad, 0x53, 0xa0, 0xe9, 0x93, 0xe4, 0xe0, 0x22, 0xd4, 0xff, 0xad, 0xcf, 0x7f, 0x05, 0x00, 0x00,
	0xff, 0xff, 0xef, 0x66, 0xda, 0x0c, 0x94, 0x05, 0x00, 0x00,
}
